config/routes.rb
Rails.application.routes.draw do
  # Homepage
  root "notices#index"

  # About page
  get "about" => "static#about"

  # Notifications
  get "notifications" => "notifications#dashboard"
  post "notifications" => "notifications#charge"
  put "notifications/pause" => "notifications#pause"

  # Authentication
  post "authentication" => "authentication#phone", as: :authentication_phone
  get "authentication/:phone" => "authentication#token", as: :authentication_token
  post "authentication/:phone" => "authentication#create"
  delete "authentication" => "authentication#destroy", as: :logout

  # Jump link for SMS
  get "n/:id" => "notices#jump"

  # SEO redirects from old site version
  get "yA399zrmM0" => redirect("n/p0k3b")
  get "yA39EAzJlK" => redirect("n/7lArW")
  get "yA39gkMeqB" => redirect("n/6l2Qb")
  get "yA39ARkX4O" => redirect("n/M5d0a")
  get "yA3z7evlWr" => redirect("n/xxDEg")
  get "yA3z44y3Wx" => redirect("n/5lzWN")
  get "yA3BPgvrKQ" => redirect("n/3lgkn")
  get "yA3BWdJY8D" => redirect("n/nyoXr")
  get "yA3BWbol9g" => redirect("n/yBp2W")
  get "yA3ymA8GmB" => redirect("n/GAObW")

  # Fallback for all notices
  get ":id" => "notices#show", as: :notice

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notice.rb
class Notice < ApplicationRecord
  has_many :notice_notifications, dependent: :destroy
  has_many :users, through: :notice_notifications

  scope :current, -> {
          where(
            "start_date <= ? AND end_date >= ?",
            Date.today,
            Date.today,
          ).order(posted_date: :desc)
        }
  scope :recent, -> { order(posted_date: :desc).limit(10) }

  before_validation :set_slug, unless: -> { slug? }

  def self.import_whitehouse(page = nil)
    data = Whitehouse::Crawler.flag_proclamations(page)
    data.map do |d|
      Notice.where(d.slice(:title, :hashid)).first_or_create do |notice|
        notice.assign_attributes(d)
      end
    end
  end

  def self.pull_notices
    import_whitehouse
  end

  def set_slug
    self.slug = "#{hashid}-#{title.gsub(/\s/, "-").gsub(/[^\w-]/, "").downcase}"
  end

  def to_param
    slug
  end

  def self.send_current_notifications
    current.each(&:send_notifications)
  end

  def send_notifications
    users_needing_notifications.each do |user|
      Sms.send(user.phone, sms_body)
      notice_notifications.create(user: user)
    end
  end

  def users_needing_notifications
    User.active.where(
      "id NOT IN (" +
      "SELECT user_id FROM notice_notifications WHERE notice_notifications.notice_id = ?" +
      ")",
      id,
    )
  end

  def sms_body
    body = "#{scope} flag lowered: ~!~ https://halfstaff.co/n/#{hashid}"
    details = "#{title}. #{summary}"
    body.gsub("~!~", details.truncate(160 - body.length + 3))
  end
end

app/models/notice_notification.rb
class NoticeNotification < ApplicationRecord
  belongs_to :notice
  belongs_to :user
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user

  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :payments

  scope :active, -> { where(active: true).where("expires_at > ?", Time.now) }

  validates(
    :phone,
    presence: true,
    phone: true,
  )

  def self.authenticate(phone, token)
    user = where(
      phone: Phone.sanitize(phone),
      token: token,
    ).where("token_generated_at > ?", 1.hour.ago).first

    user&.reset_login

    user
  end

  def active?
    stripe_id && expires_at > Time.now
  end

  def extend_user(years)
    self.expires_at = Time.now if expires_at.nil? || expires_at < Time.now
    self.expires_at += years.years
    self.active = true
    save

    Sms.send(
      phone,
      "Your flag notifications are now extended until #{expires_at.strftime("%B %-d, %Y")}",
    )
  end

  def formatted_phone
    Phone.format(phone)
  end

  def issue_token
    return if last_texted_about_login_at && last_texted_about_login_at > 10.minutes.ago

    if token_generated_at.nil? || token_generated_at < 1.hour.ago
      self.token = rand(9999).to_s.center(4, rand(9).to_s)
      self.token_generated_at = Time.now
      save
    end
    Sms.send(phone, "Your HalfStaff.co verification code is: #{token}")
    self.last_texted_about_login_at = Time.now
    save
  end

  def reset_login
    self.last_texted_about_login_at = nil
    self.token_generated_at = nil
    self.token = nil
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_flag_status

  helper_method :signed_in?, :current_user

  layout :set_layout

  def set_flag_status
    @currently_half_staff = !Notice.current.empty?
    @page_half_staff = @currently_half_staff
  end

  def lower_page_flag
    @page_half_staff = true
  end

  def current_user
    @current_user ||= User.where(id: session[:user]).first
  end

  def signed_in?
    !current_user.nil?
  end

  protected

  def set_layout
    "flag"
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  # Receive a phone number, send a token, redirect to token page
  def phone
    unless Phone.valid?(params[:phone])
      flash[:error] = "Invalid phone number"
      return redirect_to(notifications_path)
    end

    number = Phone.sanitize(params[:phone])
    User.where(phone: number).first_or_create.issue_token
    redirect_to authentication_token_path(number)
  end

  # Display token entry page
  def token
    @phone = params[:phone]
    @formatted_phone = Phone.format(@phone)
  end

  # Receive a token, perform authentication, redirect to notifications
  def create
    @user = User.authenticate(
      params[:phone],
      params[:token],
    )

    if @user
      session[:user] = @user.id
      flash[:notice] = "Successfully verified your phone number"
      redirect_to :notifications
    else
      flash[:error] = "Invalid token, please try again"
      redirect_to authentication_token_path(params[:phone])
    end
  end

  # Log out
  def destroy
    session[:user] = nil
    redirect_to notifications_path
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :lower_page_flag, only: [:show]

  def index
    @current_notices = Notice.current
    @recent_notices = Notice.recent
  end

  def show
    @notice = Notice.where(slug: params[:id]).first!
  rescue ActiveRecord::RecordNotFound
    redirect_to :root
  end

  def jump
    @notice = Notice.where(hashid: params[:id]).first
    redirect_to(@notice || :root, status: 301)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def dashboard
    if signed_in?
      render :manage
    else
      render :signin
    end
  end

  def charge
    action = ExtendNotifications.new(
      user: current_user,
      email: params[:email],
      token: params[:token],
      years: params[:years].to_i,
    )

    if action.extend_subscription
      flash[:notice] = "Successfully extended notifications by #{years} #{"years".pluralize(years)}"
    end

    redirect_to notifications_path
  rescue Stripe::StripeError => e
    flash[:error] = e.message
    redirect_to notifications_path
  end

  def pause
    action = PauseNotifications.new(
      user: current_user,
    )

    flash[:notice] = if action.pause
                       "Successfully paused notifications"
                     else
                       "Successfully resumed notifications"
                     end

    redirect_to notifications_path
  end

  protected

  def notification_params
    params.permit(:active)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="apple-mobile-web-app-title" content="Half Staff">
<meta name="application-name" content="Half Staff">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/authentication/token.html.erb
<% content_for :title do %>Verify your number<% end %>
<div class="card">
  <div class="title">
    <h3>Verify <%= @formatted_phone %></h3>
  </div>
  <div class="text">
    <p>
      We sent you a text message at <strong><%= @formatted_phone %></strong> with a verification token.  You should receive it within a few minutes.
    </p>

    <%= form_tag authentication_token_path, method: :post do %>
      <%= hidden_field_tag :phone, @phone %>
      <p>
        <label>
          Verification Token
          <%= text_field_tag :token, nil, maxlength: 4, placeholder: 'XXXX', autocomplete: 'off', inputmode: 'numeric', pattern: '[0-9]*' %>
        </label>
      </p>

      <p><%= submit_tag 'Verify' %></p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title><%= content_for?(:title) ? "#{yield(:title)} | Half Staff" : 'Half Staff' %></title>

  <% if content_for(:description) %>
  <meta name="description" content="<%= yield(:description) %>">
  <% end %>

  <%= render 'favicon' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://fonts.googleapis.com/css?family=Cairo:300,400,600,700" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <script src="https://checkout.stripe.com/checkout.js"></script>
  <script>
    window.STRIPE_TOKEN = '<%= Rails.configuration.stripe[:key] %>';
    window.STRIPE_LOGO = '<%= image_path 'icon.svg'  %>';
  </script>
</head>

<body class="<% if @page_half_staff %>halfstaff<% else %>fullstaff<% end %>">
  <header class="header">
    <a class="title" href="/"><small>currently at</small><br><% if @currently_half_staff %>Half<% else %>Full<% end %> Staff</a>
    <ul class="menu">
      <li><a href="/about/">About</a></li>
      <li class="notifications"><a href="/notifications/">Notifications</a></li>
      <% if signed_in? %>
        <li class="logout"><%= button_to 'Logout', logout_path, method: :delete %></li>
      <% end %>
    </ul>
  </header>
  <% if flash[:notice] || flash[:error] %>
    <div class="flash">
      <div class="card">
        <div class="text">
          <% if flash[:notice] %><p class="notice"><%= flash[:notice] %></p><% end %>
          <% if flash[:error] %><p class="error"><%= flash[:error] %></p><% end %>
        </div>
      </div>
    </div>
  <% end %>
  <main class="main">
    <%= content_for?(:content) ? yield(:content) : yield %>
  </main>
  <%= javascript_include_tag 'application' %>
  <script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-79594103-1', 'auto');
    ga('send', 'pageview');</script>
</body>
</html>

app/views/layouts/flag.html.erb
<% content_for :content do %>
  <%= render partial: 'shared/flag' %>
  <div class="cards">
    <%= yield %>
  </div>
<% end %>
<%= render template: 'layouts/application' %>

app/views/notices/_notice.html.erb
<% cache [:v1, :partial, notice] do %>
  <div class="card">
    <div class="title">
      <h3><%= notice.posted_date.strftime('%B %-d, %Y') %></h3>
      <%= link_to notice do %>
        <h2><%= notice.title %></h2>
      <% end %>
    </div>
    <div class="text">
      <%= notice.summary %>
    </div>
    <div class="meta">
      <div class="time">
        <div class="label">Start</div>
        <div><time><%= notice.start_date.strftime('%B %-d, %Y') %></time></div>
      </div>
      <% if notice.end_date %>
        <div class="time">
          <div class="label">End</div>
          <div>
            <time><%= notice.end_date.strftime('%B %-d, %Y') %></time>
            <% case notice.end_time %>
            <% when "noon" %>
            until noon
            <% when "sunset" %>
            until sunset
            <% end %>
          </div>
        </div>
      <% end %>
      <% if notice.notice_type == 'interment' %>
        <div class="time">
          <div class="label">End</div>
          <div>The day of interment</div>
        </div>
      <% end %>
    </div>
    <div class="actions">
      <a class="more-info" href="<%= notice.url %>" target="_blank">
        Details
      </a>
    </div>
  </div>
<% end %>

app/views/notices/index.html.erb
<% content_for :title do %><% if @currently_half_staff %>The flag is lowered<% else %>The flag is at full staff<% end %><% end %>
<% content_for :description do %><%= (@currently_half_staff ? "#{@current_notices[0].title} - #{@current_notices[0].summary}" : "The flag is at full staff. Browse recent flag notices and read about flag etiquette.").truncate(150) %><% end %>

<% cache [:v1, @current_notices] do %>
  <%=
    render(
      collection: @current_notices,
      partial: :notice,
      as: :notice,
      show_summary: false,
      action_type: :details
    )
  %>
<% end %>

<% cache [:v1, @recent_notices] do %>
<div class="card recent">
  <div class="title">
    <h3>Recent Notices</h3>
  </div>
  <div class="text">
    <% @recent_notices.each do |notice| %>
    <div class="recent-notice">
      <%= link_to notice.title, notice %>
      <small><%= notice.start_date.strftime('%B %-d, %Y') %></small>
    </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/notices/show.html.erb
<% content_for :title do %><%= @notice.start_date.strftime('%B %-d, %Y')%> - <%= @notice.title %><% end %>
<% content_for :description do %><%= @notice.summary.truncate(150) %><% end %>
<%= render partial: 'notice', locals: { notice: @notice } %>

app/views/notifications/manage.html.erb
<% content_for :title do %>Manage Notifications<% end %>
<div class="card">
  <div class="title">
    <h3>Your Notifications</h3>
  </div>
  <div class="text">
    <p>
      Your number is <strong><%= current_user.formatted_phone %></strong>.
    </p>

    <% if current_user.expires_at %>
      <% if current_user.expires_at > DateTime.now %>
        <% if current_user.active %>
          <p>
            Notifications are <strong>active</strong> and will continue until <strong><span class="date"><%= current_user.expires_at.strftime('%B %-d, %Y') %></span></strong>.
          </p>

          <p>
            <%= button_to 'Pause', notifications_pause_path, method: :put, form_class: 'button-inline' %>
            <%= button_to 'Logout', logout_path, method: :delete, form_class: 'button-inline' %>
          </p>
        <% else %>
          <p>
            Notifications are <strong>paused</strong> but are paid through <strong><span class="date"><%= current_user.expires_at.strftime('%B %-d, %Y') %></span></strong>.
          </p>

          <p>
            <%= button_to 'Resume', notifications_pause_path, method: :put, form_class: 'button-inline' %>
            <%= button_to 'Logout', logout_path, method: :delete, form_class: 'button-inline' %>
          </p>
        <% end %>
      <% else %>
        <p>
          Notifications are <strong>inactive</strong> and expired at <strong><span class="date"><%= current_user.expires_at.strftime('%B %-d, %Y') %></span></strong>.
          To resume, use the button below to extend notifications.
        </p>
      <% end %>
    <% else %>
      <p>Receive a text message any time the US flag is lowered.  <strong>$2 / year</strong> one-time purchase, does not renew.</p>
    <% end %>
  </div>
</div>

<div class="card">
  <div class="title">
    <h3>Extend Notifications</h3>
  </div>
  <div class="text">
    <%= form_tag notifications_path, method: :post, id: 'stripe-form', class: 'stripe-form' do %>
      <%= hidden_field_tag :token, nil, id: 'stripe-token' %>
      <%= hidden_field_tag :email, nil, id: 'stripe-email' %>
      <div class="stripe-extend">
        <span class="stripe-years">
          <select id="stripe-years" name="years">
            <option value="1">1 year ($2)</option>
            <option value="2">2 years ($4)</option>
            <option value="3">3 years ($6)</option>
            <option value="4">4 years ($8)</option>
            <option value="5">5 years ($10)</option>
          </select>
        </span>

        <p>
          <a class="stripe-button" id="stripe-button"><span>Pay with Stripe</span></a>
        </p>
      </div>
    <% end %>

    <p>If you have any issues or questions, or if you need to change your phone number, please <a href="mailto:jacobwgillespie@gmail.com">send an email</a> and we will get back with you as soon as possible.</p>
  </div>
</div>

<% if !current_user.payments.empty? %>
<div class="card">
  <div class="title">
    <h3>Payment History</h3>
  </div>
  <div class="text">
    <div class="payment-history">
      <% current_user.payments.each do |payment| %>
        <div class="payment-entry">
          <div><span class="date"><%= payment.created_at.strftime('%B %-d, %Y') %></span></div>
          <div>Extended <%= pluralize(payment.years, 'year') %></div>
          <div><%= number_to_currency(payment.amount / 100) %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/notifications/signin.html.erb
<% content_for :title do %>Notifications<% end %>
<div class="card">
  <div class="title">
    <h3>Your Notifications</h3>
  </div>
  <div class="text">
    <p>
      Subscribe to receive text messages notifying you when the flag is lowered to keep informed and know when to lower your own flags. $2 / year.</p>
    </p>

    <p>
      <%= image_tag 'sms.png' %>
    </p>

    <%= form_tag authentication_phone_path, method: :post do %>
      <p>
        <label>
          Phone Number
          <%= telephone_field_tag :phone %>
        </label>
      </p>

      <p><%= submit_tag 'Sign in / Sign up' %></p>
    <% end %>
  </div>
</div>

app/views/shared/_flag.html.erb
<svg class="flag" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 57 144">
<title>American Flag</title>
<g>
  <g>
    <g>
      <g class="banner">
        <path class="cls-1" d="M40,43H57v3H40V43Z"/>
        <path class="cls-2" d="M40,40H57v3H40V40Z"/>
        <path class="cls-6" d="M8,7H28V25H8V7Z"/>
        <path class="cls-7" d="M14,9.28l0.93,1.88L17,11.46l-1.5,1.47L15.85,15,14,14l-1.86,1,0.36-2.07L11,11.46l2.08-.3L14,9.28"/>
        <path class="cls-7" d="M22,9l0.93,1.88L25,11.19l-1.5,1.47,0.35,2.07-1.86-1-1.86,1,0.35-2.07L19,11.19l2.08-.3L22,9"/>
        <path class="cls-7" d="M14,16.28l0.93,1.88L17,18.46l-1.5,1.47L15.85,22,14,21l-1.86,1,0.36-2.07L11,18.46l2.08-.3L14,16.28"/>
        <path class="cls-7" d="M22,16l0.93,1.88L25,18.18l-1.5,1.47,0.35,2.07-1.86-1-1.86,1,0.35-2.07L19,18.18l2.08-.3L22,16"/>
        <path class="cls-9" d="M40,46V40h5l-5,6"/>
        <path class="cls-10" d="M28,7H45v3H28V7Z"/>
        <path class="cls-11" d="M28,10H45v3H28V10Z"/>
        <path class="cls-10" d="M28,13H45v3H28V13Z"/>
        <path class="cls-11" d="M28,16H45v3H28V16Z"/>
        <path class="cls-10" d="M28,19H45v3H28V19Z"/>
        <path class="cls-11" d="M28,22H45v3H28V22Z"/>
        <path class="cls-1" d="M45,13H57v3H45V13Z"/>
        <path class="cls-2" d="M45,16H57v3H45V16Z"/>
        <path class="cls-1" d="M45,19H57v3H45V19Z"/>
        <path class="cls-2" d="M45,22H57v3H45V22Z"/>
        <path class="cls-1" d="M45,25H57v3H45V25Z"/>
        <path class="cls-2" d="M45,28H57v3H45V28Z"/>
        <path class="cls-1" d="M45,31H57v3H45V31Z"/>
        <path class="cls-1" d="M45,37H57v3H45V37Z"/>
        <path class="cls-2" d="M45,34H57v3H45V34Z"/>
        <path class="cls-10" d="M8,25H45v3H8V25Z"/>
        <path class="cls-11" d="M8,28H45v3H8V28Z"/>
        <path class="cls-10" d="M8,31H45v3H8V31Z"/>
        <path class="cls-11" d="M8,34H45v3H8V34Z"/>
        <path class="cls-10" d="M8,37H45v3H8V37Z"/>
      </g>

      <path class="cls-3" d="M12,144H0v-2.3A0.7,0.7,0,0,1,.7,141H11.3a0.7,0.7,0,0,1,.7.7V144"/>
      <path class="cls-4" d="M7,31a1,1,0,0,0,1,1V30a1,1,0,0,0-1,1"/>
      <path class="cls-3" d="M4,7H8V139H4V7Z"/>
      <path class="cls-5" d="M2,138h8v3H2v-3Z"/>
      <path class="cls-8" d="M10,4A4,4,0,1,1,6,0a4,4,0,0,1,4,4"/>
    </g>
  </g>
</g>
</svg>